apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wise-words-hpa
  labels:
    app: wise-words-app
    app.kubernetes.io/name: wise-words-on-demand
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: quoteapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wise-words-app
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
