apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quoteapp

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml

commonLabels:
  app.kubernetes.io/name: wise-words-on-demand
  app.kubernetes.io/part-of: quoteapp

images:
  - name: wise-words-on-demand
    newName: wisewordsdevacr.azurecr.io/wise-words-webapp
    newTag: latest

replicas:
  - name: wise-words-app
    count: 2
