name: Infrastructure CI

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'terraform/**'
      - '.github/workflows/infrastructure-ci.yml'
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - '.github/workflows/infrastructure-ci.yml'

jobs:
  terraform-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check for terraform changes
      id: check-terraform
      run: |
        if [ -d "terraform" ] && [ "$(find terraform -name "*.tf" -o -name "*.tfvars" | wc -l)" -gt 0 ]; then
          echo "terraform_changed=true" >> $GITHUB_OUTPUT
        else
          echo "terraform_changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    - name: Terraform Format Check
      if: steps.check-terraform.outputs.terraform_changed == 'true'
      run: |
        cd terraform
        terraform fmt -check -recursive

    - name: Terraform Init
      if: steps.check-terraform.outputs.terraform_changed == 'true'
      run: |
        cd terraform
        terraform init -backend=false

    - name: Terraform Validate
      if: steps.check-terraform.outputs.terraform_changed == 'true'
      run: |
        cd terraform
        terraform validate
