name: Webapp Release

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'app_factory.py'
      - 'config.py'
      - 'test_app.py'
      - 'requirements*.txt'
      - 'Dockerfile'
      - 'templates/**'
    tags:
      - 'webapp-v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

env:
  REGISTRY: wisewordsdevacr.azurecr.io
  IMAGE_NAME: wise-words-webapp

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8

    - name: Run linting
      run: |
        flake8 app_factory.py app/ config.py test_app.py --max-line-length=100 --exclude=venv

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and compile app
      run: |
        echo "Building Flask application..."
        python -c "
        from app_factory import create_app
        app = create_app()
        print('✅ Flask app created successfully')
        print(f'App name: {app.name}')
        print(f'Debug mode: {app.debug}')
        print('✅ App build completed successfully')
        "

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt

    - name: Run tests
      run: |
        python -m pytest test_app.py -v --tb=short

    - name: Test app factory
      run: |
        python -c "from app_factory import create_app; app = create_app(); print('App factory test passed')"

  docker-build-push:
    needs: [lint, build, test]
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
      image-digest: ${{ steps.build.outputs.digest }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      run: |
        az acr login --name wisewordsdevacr

    - name: Verify Dockerfile exists
      run: |
        ls -la Dockerfile
        echo "Dockerfile contents:"
        head -10 Dockerfile

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=tag,prefix=webapp-
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  create-release:
    needs: docker-build-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/webapp-v') || github.ref == 'refs/heads/main')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate Release Tag
      id: release-tag
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          # For main branch pushes, create a timestamp-based tag
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          echo "tag_name=webapp-v1.0.0-${TIMESTAMP}" >> $GITHUB_OUTPUT
          echo "release_name=Webapp Release v1.0.0-${TIMESTAMP}" >> $GITHUB_OUTPUT
        else
          # For tag pushes, use the existing tag
          echo "tag_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          echo "release_name=Webapp Release ${{ github.ref_name }}" >> $GITHUB_OUTPUT
        fi

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.release-tag.outputs.tag_name }}
        release_name: ${{ steps.release-tag.outputs.release_name }}
        body: |
          ## ${{ steps.release-tag.outputs.release_name }}

          ### Docker Image
          - **Image**: `wisewordsdevacr.azurecr.io/wise-words-webapp:${{ steps.release-tag.outputs.tag_name }}`
          - **Digest**: `${{ needs.docker-build-push.outputs.image-digest }}`

        draft: false
        prerelease: false
