name: Webapp Infrastructure CI

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'webapp-infra/**'
      - '.github/workflows/webapp-infra-ci.yml'
  push:
    branches: [ main ]
    paths:
      - 'webapp-infra/**'
      - '.github/workflows/webapp-infra-ci.yml'

jobs:
  terraform-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check for webapp-infra changes
      id: check-webapp-infra
      run: |
        if [ -d "webapp-infra" ] && [ "$(find webapp-infra -name "*.tf" -o -name "*.tfvars" | wc -l)" -gt 0 ]; then
          echo "webapp_infra_changed=true" >> $GITHUB_OUTPUT
        else
          echo "webapp_infra_changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    - name: Terraform Format Check
      if: steps.check-webapp-infra.outputs.webapp_infra_changed == 'true'
      run: |
        cd webapp-infra/terraform
        terraform fmt -check -recursive

    - name: Terraform Init
      if: steps.check-webapp-infra.outputs.webapp_infra_changed == 'true'
      run: |
        cd webapp-infra/terraform
        terraform init -backend=false

    - name: Terraform Validate
      if: steps.check-webapp-infra.outputs.webapp_infra_changed == 'true'
      run: |
        cd webapp-infra/terraform
        terraform validate
